import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
        <nav className={"flex flex-row justify-end gap-x-5 p-4 bg-slate-900 bg-opacity-95"}>
            <a href="/">Home</a>
            <a href="/about">About</a>
        </nav>
        {children}
    </body>
    </html>
  );
}
